### ISSUE TITLE
Mobile Styling

### ISSUE THREAD

**Issue by rohansree** [cse110-fa21-group21/cse110-fa21-group21#106]
Currently on a device without a wide view (e.g. a mobile device), our styling on almost every page breaks down. Additionally, not sure how to make the filters start off hidden on a mobile device.

**Comment by dwk002** [comment]
Especially for Recipe Viewer & Shopping List & Favorite List! (lol ig that's everything)

**Comment by angelinale1104** [comment]
TO-DO tasks. Responsive Design for:
- [ ] Home Page
- [ ] Search result page
- [ ] Recipe Viewer
- [ ] Shopping List
- [ ] Favorite List

**Comment by dwk002** [comment]
> TO-DO tasks. Responsive Design for:
> 
> * [x]  Home Page
> * [ ]  Search result page
> * [ ]  Recipe Viewer
> * [ ]  Shopping List
> * [ ]  Favorite List

Angelina is currently working on shopping List!

**Comment by angelinale1104** [comment]
Since I believe this issue is done, I am gonna close it! :)
