### ISSUE TITLE
Update logo.

### ISSUE THREAD

**Issue by hgnguyenucsd** [cse110-fa21-group21/cse110-fa21-group21#57]
Maybe change the logo we have for the home page to one of the pictures that Maggie drew.

**Comment by JonathanBocanegra** [comment]
We thought it would be better to replace our group logo with the cooking girls Maggie made a while ago. Our logo doesn't really speak food.

**Comment by angelinale1104** [comment]
I agree. I will tag Maggie (@yexiu52937) here to ask about the drawing. @yexiu52937 Do you have a drawing of the cooking girl with a transparent background that we can use for the logo?

**Comment by yexiu52937** [comment]
I get give u one by tonight

**Comment by angelinale1104** [comment]
@yexiu52937 Sounds good, if you have time, you can replace the logo on your end too! If not, I can do it later tonight or tomorrow. Thanks!
