### ISSUE TITLE
Styling-Nav Bar

### ISSUE THREAD

**Issue by dwk002** [cse110-fa21-group21/cse110-fa21-group21#98]
- [ ] Adding more style to just the brown bar that is at the top of the page
- [x] Adding more style to the "search button?
- [x] Also, I think it would make sense to add the icon to collapse the filter list on the navbar instead of where it is now? (From: James: Hmm, not sure~ I was thinking it should be further down from the navbar~)
(From Angelina: That works too! If so, then ignore this task then :) )
- [ ] **[If time allows]** I think it would be great if you can draw something cute for the collapsible icon (similar style to the home, favorite list and shopping list icon)

![image](https://user-images.githubusercontent.com/72471050/145134551-7f370e41-288e-438f-ba4f-9608e34c7085.png)

**Comment by angelinale1104** [comment]
Hey Maggie (@yexiu52937), do you want to handle this since you worked on the nav bar?

**Comment by yexiu52937** [comment]
OK I'll do it tonight.
