### ISSUE TITLE
Styling-Shopping List

### ISSUE THREAD

**Issue by dwk002** [cse110-fa21-group21/cse110-fa21-group21#99]
- [ ] Styling for Ingredient List in Shopping List Page
- [x] Styling for "Add to Shopping List" button inside of Recipe Viewer, on the bottom of the ingredient list

Overall, make the Shopping List page looks nice! :)

**Comment by angelinale1104** [comment]
@lba353 I can handle the "Add to Shopping List" button inside the recipe viewer. So you just have to focus on the styling for the Shopping List. If you have time after you are done, please help Cade with responsive design. Thanks! :)

**Comment by angelinale1104** [comment]
Update: Ludvig and I just talked on Slack. He thinks that the current shopping list looks good as is so he won't make any styling changes to the shopping list. He said that he would focus on helping Cade with the responsive design and other tasks if needed. Thus, I will close this issue :)

**Comment by dwk002** [comment]
Sounds good to me! Mobile Response does need a lot of work!
